### ISSUE TITLE
Push failure

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/pfish#22]
```
Devins-MBP:aq-covid19-test devin$ pfish push -c 'Diagnostic RT-qPCR' -o 'Run qPCR'
Traceback (most recent call last):
  File "/script/pyfish.py", line 209, in <module>
    main()
  File "/script/pyfish.py", line 37, in main
    args.func(args)
  File "/script/pyfish.py", line 202, in do_push
    select_operation_type(aq, category_path, args.operation_type)
  File "/script/push.py", line 41, in select_operation_type
    push(aq, path, operation_type_code_names())
  File "/script/push.py", line 164, in push
    logging.info("writing file {}".format(parent_object.name))
AttributeError: 'list' object has no attribute 'name'
```

**Comment by dvnstrcklnd** [comment]
Seems to have been fixed by new version on Dockerhub
