### ISSUE TITLE
OperationType push failure: appears to run, but doesn't add any content

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/pfish#23]
I created an OperationType on my Docker instance so that I can push some code that Cannon wrote:
```bash
Devins-MBP:aq-covid19-test devin$ pfish create -c 'Diagnostic RT-qPCR' -o 'Rehydrate Patient Sample'
INFO:root:writing operation type Rehydrate Patient Sample
WARNING:root:Missing Rehydrate Patient Sample code for operation type test
Devins-MBP:aq-covid19-test devin$ pfish push -c 'Diagnostic RT-qPCR' -o 'Rehydrate Patient Sample'
Traceback (most recent call last):
  File "/script/pyfish.py", line 209, in <module>
    main()
  File "/script/pyfish.py", line 37, in main
    args.func(args)
  File "/script/pyfish.py", line 202, in do_push
    select_operation_type(aq, category_path, args.operation_type)
  File "/script/push.py", line 41, in select_operation_type
    push(aq, path, operation_type_code_names())
  File "/script/push.py", line 164, in push
    logging.info("writing file {}".format(parent_object.name))
AttributeError: 'list' object has no attribute 'name'
```
I tried pushing the code, but got hung up with a bug in pfish. After that was fixed, I tried pushing again:
```bash
Devins-MBP:aq-covid19-test devin$ pfish push -c 'Diagnostic RT-qPCR' -o 'Rehydrate Patient Sample'
INFO:root:writing file Rehydrate Patient Sample
INFO:root:writing file Rehydrate Patient Sample
INFO:root:writing file Rehydrate Patient Sample
INFO:root:writing file Rehydrate Patient Sample
WARNING:root:Error [Errno 2] No such file or directory: '/wd/diagnostic_rt_qpcr/operation_types/rehydrate_patient_sample/test.rb' writing file test.rb file does not exist
Devins-MBP:aq-covid19-test devin$ ls
ABOUT.md		diagnostic_rt_qpcr	object_types
LICENSE.md		docs			operation_types
README.md		index.html		sample_types
aq-covid19-test.aq	js
config.json		modified_cdc_protocol
Devins-MBP:aq-covid19-test devin$ ls diagnostic_rt_qpcr/operation_types/rehydrate_patient_sample
cost_model.rb		documentation.rb	protocol.rb
definition.json		precondition.rb
Devins-MBP:aq-covid19-test devin$ touch diagnostic_rt_qpcr/operation_types/rehydrate_patient_sample/test.rb
Devins-MBP:aq-covid19-test devin$ pfish push -c 'Diagnostic RT-qPCR' -o 'Rehydrate Patient Sample'
INFO:root:writing file Rehydrate Patient Sample
INFO:root:writing file Rehydrate Patient Sample
INFO:root:writing file Rehydrate Patient Sample
INFO:root:writing file Rehydrate Patient Sample
INFO:root:writing file Rehydrate Patient Sample
Devins-MBP:aq-covid19-test devin$ more modified_cdc_protocol/operation_types/rehydratepatientsample/protocol.rb
# typed: false
# frozen_string_literal: true

needs 'Standard Libs/PlanParams'
needs 'Standard Libs/Debug'
needs 'Standard Libs/Pipettors'
needs 'Standard Libs/Units'
needs 'Standard Libs/AssociationManagement'
```

However, when looking at the protocol code through the GUI it is completely empty.

**Comment by dvnstrcklnd** [comment]
This seems to have been resolved.
