### ISSUE TITLE
Push by path

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/pfish#25]
I thin it would be useful to be able to push by path, e.g.
```bash
pfish push -p diagnostic_rt_qpcr/libraries/diagnosticrtqpcrdebug
```
because it is easy to use `git status` to see what's new and then copy and paste these into commands. Translating to the normal names is sometimes a pain.

**Comment by dvnstrcklnd** [comment]
This doesn't seem to work as intended: 
```
Devins-MBP:protocol-base devin$ pfish push -d standard_libs/
Traceback (most recent call last):
  File "/script/pyfish.py", line 301, in <module>
    main()
  File "/script/pyfish.py", line 33, in main
    args.func(args)
  File "/script/pyfish.py", line 257, in do_push
    instance.push(session=session, path=path)
  File "/script/instance.py", line 60, in push
    category.push(session, path)
TypeError: push() takes 0 positional arguments but 2 were given
```
However:
```
Devins-MBP:protocol-base devin$ pfish push -c 'Standard Libs'
INFO:AqHTTP@http://localhost:REQUEST: (t=0.015162s)  POST http://localhost/json
.
.
.
```
The catch is that this command loads **everything**, not just standard libs.

**Comment by dvnstrcklnd** [comment]
I mean, it's actually pretty great at loading everything. It just doesn't have the expected control.

**Comment by dvnstrcklnd** [comment]
I am also unclear on how to push operation types and sample types.
