### ISSUE TITLE
[Bug] push gets hung up on .DS_Store

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/pfish#41]
```bash
Devins-MBP:aq-genome-center devin$ pfish push -c 'Covid Surveillance'
INFO:AqHTTP@http://localhost:REQUEST: (t=0.013001s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.008998s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.031253s)  POST http://localhost/libraries.json
.
.
.
INFO:AqHTTP@http://localhost:REQUEST: (t=0.009501s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.033042s)  POST http://localhost/libraries.json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.009793s)  POST http://localhost/json
Traceback (most recent call last):
  File "/script/pyfish.py", line 301, in <module>
    main()
  File "/script/pyfish.py", line 33, in main
    args.func(args)
  File "/script/pyfish.py", line 251, in do_push
    category.push(session=session, path=category_path)
  File "/script/category.py", line 74, in push
    operation_type.push(
  File "/script/operation_type.py", line 167, in push
    if not definition.has_definition(path):
  File "/script/definition.py", line 10, in has_definition
    return 'definition.json' in os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/wd/covid_surveillance/operation_types/_ds_store'
Devins-MBP:aq-genome-center devin$ 
```

**Comment by cashmonger** [comment]
Closing -- fixed by error handling added in PR#51.
