### ISSUE TITLE
push fails 

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/pfish#60]
When I pull an operation type from production and attempt to push it to a mostly empty instance that doesn't have this OT or any sample types or object types, I get this:
```bash
Devins-MBP:temp2 devin$ pfish pull -n production -c 'Yeast Display' -o 'Innoculate Yeast Library'
INFO:AqHTTP@http://52.27.43.242/:REQUEST: (t=0.168737s)  POST http://52.27.43.242/json
INFO:AqHTTP@http://52.27.43.242/:CALLBACK 'OperationType(rid=0)' made a WHERE request for 'FieldType'
INFO:AqHTTP@http://52.27.43.242/:REQUEST: (t=0.234753s)  POST http://52.27.43.242/json
INFO:root:writing object type Yeast Plate
INFO:root:writing object type Yeast Library Glycerol Stock
INFO:root:writing object type Labeled Yeast Library Suspension
INFO:root:writing object type Divided Yeast Plate
INFO:root:writing object type Labeled Yeast Strain Suspension
INFO:root:writing object type 800 mL Liquid
INFO:root:writing object type Yeast 5ml culture
INFO:root:writing object type Yeast Library Liquid Culture
INFO:root:writing sample type Yeast Strain
INFO:root:writing sample type DNA Library
INFO:root:writing sample type DNA Library
INFO:root:writing sample type Yeast Strain
INFO:root:writing sample type Yeast Strain
INFO:root:writing sample type Media
INFO:root:writing sample type Yeast Strain
INFO:root:writing sample type DNA Library
INFO:root:Writing operation type Innoculate Yeast Library
INFO:AqHTTP@http://52.27.43.242/:REQUEST: (t=0.219672s)  POST http://52.27.43.242/json
INFO:AqHTTP@http://52.27.43.242/:REQUEST: (t=0.222693s)  POST http://52.27.43.242/json
INFO:AqHTTP@http://52.27.43.242/:REQUEST: (t=0.221491s)  POST http://52.27.43.242/json
INFO:AqHTTP@http://52.27.43.242/:REQUEST: (t=0.1813s)  POST http://52.27.43.242/json
INFO:AqHTTP@http://52.27.43.242/:REQUEST: (t=0.177855s)  POST http://52.27.43.242/json
Devins-MBP:temp2 devin$ pfish push -c 'Yeast Display' -o 'Innoculate Yeast Library'
INFO:root:Checking whether Definition File is for an Operation Type.
INFO:AqHTTP@http://localhost:REQUEST: (t=0.007929s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.005755s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.035046s)  POST http://localhost/operation_types.json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.006086s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.006072s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.005863s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.005931s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.006637s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.006835s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.006917s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.006326s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.007034s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.007399s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.006922s)  POST http://localhost/json
INFO:AqHTTP@http://localhost:REQUEST: (t=0.021783s)  PUT http://localhost/operation_types/14
TEXT: {
  "error": [
    "undefined local variable or method `ft' for #<OperationType:0x00007f698a5f3700>",
    "[\"/usr/local/bundle/gems/activemodel-4.2.11.3/lib/active_model/attribute_methods.rb:433:in `method_missing'\", \"/aquarium/app/models/operation_type.rb:222:in `block in add_new_field_type'\", \"/aquarium/app/models/operation_type.rb:221:in `collect'\", \"/aquarium/app/models/operation_type.rb:221:in `add_new_field_type'\", \"/aquarium/app/models/operation_type.rb:295:in `block in update_field_types'\", \"/aquarium/app/models/operation_type.rb:288:in `each'\", \"/aquarium/app/models/operation_type.rb:288:in `update_field_types'\", \"/aquarium/app/controllers/operation_types_controller.rb:133:in `block in update_from_ui'\", \"/usr/local/bundle/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'\", \"/usr/local/bundle/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'\", \"/usr/local/bundle/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'\", \"/usr/local/bundle/gems/activerecord-4.2.11.3/lib/active_record/transactions.rb:220:in `transaction'\", \"/aquarium/app/controllers/operation_types_controller.rb:118:in `update_from_ui'\", \"/aquarium/app/controllers/operation_types_controller.rb:147:in `update'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/abstract_controller/base.rb:198:in `process_action'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal/rendering.rb:10:in `process_action'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:117:in `call'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:505:in `call'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:92:in `__run_callbacks__'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:81:in `run_callbacks'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/abstract_controller/callbacks.rb:19:in `process_action'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal/rescue.rb:29:in `process_action'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `block in instrument'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `instrument'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'\", \"/usr/local/bundle/gems/activerecord-4.2.11.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/abstract_controller/base.rb:137:in `process'\", \"/usr/local/bundle/gems/actionview-4.2.11.3/lib/action_view/rendering.rb:30:in `process'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal.rb:196:in `dispatch'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_controller/metal.rb:237:in `block in action'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/routing/route_set.rb:43:in `serve'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/journey/router.rb:30:in `each'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/journey/router.rb:30:in `serve'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/routing/route_set.rb:817:in `call'\", \"/usr/local/bundle/gems/rack-1.6.13/lib/rack/etag.rb:24:in `call'\", \"/usr/local/bundle/gems/rack-1.6.13/lib/rack/conditionalget.rb:38:in `call'\", \"/usr/local/bundle/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/flash.rb:260:in `call'\", \"/usr/local/bundle/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:252:in `context'\", \"/usr/local/bundle/gems/rack-1.6.13/lib/rack/session/abstract/id.rb:247:in `call'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'\", \"/usr/local/bundle/gems/activerecord-4.2.11.3/lib/active_record/query_cache.rb:36:in `call'\", \"/usr/local/bundle/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:88:in `__run_callbacks__'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:81:in `run_callbacks'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'\", \"/usr/local/bundle/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:38:in `call_app'\", \"/usr/local/bundle/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:20:in `block in call'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:26:in `tagged'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/tagged_logging.rb:68:in `tagged'\", \"/usr/local/bundle/gems/railties-4.2.11.3/lib/rails/rack/logger.rb:20:in `call'\", \"/usr/local/bundle/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'\", \"/usr/local/bundle/gems/rack-1.6.13/lib/rack/methodoverride.rb:22:in `call'\", \"/usr/local/bundle/gems/rack-1.6.13/lib/rack/runtime.rb:18:in `call'\", \"/usr/local/bundle/gems/activesupport-4.2.11.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'\", \"/usr/local/bundle/gems/rack-1.6.13/lib/rack/sendfile.rb:113:in `call'\", \"/usr/local/bundle/gems/rack-cors-1.0.6/lib/rack/cors.rb:98:in `call'\", \"/usr/local/bundle/gems/railties-4.2.11.3/lib/rails/engine.rb:518:in `call'\", \"/usr/local/bundle/gems/railties-4.2.11.3/lib/rails/application.rb:165:in `call'\", \"/usr/local/bundle/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `public_send'\", \"/usr/local/bundle/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `method_missing'\", \"/usr/local/bundle/gems/puma-5.2.0/lib/puma/configuration.rb:247:in `call'\", \"/usr/local/bundle/gems/puma-5.2.0/lib/puma/request.rb:76:in `block in handle_request'\", \"/usr/local/bundle/gems/puma-5.2.0/lib/puma/thread_pool.rb:337:in `with_force_shutdown'\", \"/usr/local/bundle/gems/puma-5.2.0/lib/puma/request.rb:75:in `handle_request'\", \"/usr/local/bundle/gems/puma-5.2.0/lib/puma/server.rb:432:in `process_client'\", \"/usr/local/bundle/gems/puma-5.2.0/lib/puma/thread_pool.rb:145:in `block in spawn_thread'\"]"
  ]
}
usage: pyfish.py [-h] {create,configure,pull,push,test} ...

Create, push, pull, and test Aquarium protocols

optional arguments:
  -h, --help            show this help message and exit

subcommands:
  {create,configure,pull,push,test}
```

**Comment by cashmonger** [comment]
This should be fixed in the latest release (v. 1.2.0)

**Comment by dvnstrcklnd** [comment]
This appears to be fixed.
