### ISSUE TITLE
Test not working with -d option

### ISSUE THREAD

**Issue by dvnstrcklnd** [aquariumbio/pfish#76]
```bash
Devins-MBP:protocol-base devin$ pfish test -c 'Standard Libs' -o 'Test Test Fixtures'
INFO:root:Sending request to test Test Test Fixtures
INFO:root:Checking whether Definition File is for an Operation Type.
INFO:root:pushing file Test Test Fixtures
INFO:root:pushing file Test Test Fixtures
INFO:root:All tests passed
Devins-MBP:protocol-base devin$ pfish test -d 'standard_libs/operation_types/test_test_fixtures'
INFO:root:Checking whether Definition File is for an Operation Type.
INFO:root:Sending request to test <function name at 0x7f3cfe21b280>
INFO:root:Checking whether Definition File is for an Operation Type.
INFO:root:pushing file Test Test Fixtures
INFO:root:pushing file Test Test Fixtures
Traceback (most recent call last):
  File "/script/pyfish.py", line 327, in <module>
    main()
  File "/script/pyfish.py", line 33, in main
    args.func(args)
  File "/script/pyfish.py", line 323, in do_test
    instance.run_tests(session=session, path=path, timeout=args.timeout)
  File "/script/instance.py", line 94, in run_tests
    operation_type.run_test(
  File "/script/operation_type.py", line 279, in run_test
    retrieved_operation_type = get_operation_type(
  File "/script/operation_type.py", line 53, in get_operation_type
    retrieved_operation_type = session.OperationType.where(
  File "/usr/local/lib/python3.9/site-packages/pydent/interfaces.py", line 650, in where
    return self.array_query(
  File "/usr/local/lib/python3.9/site-packages/pydent/interfaces.py", line 587, in array_query
    res = self._post_json(query)
  File "/usr/local/lib/python3.9/site-packages/pydent/interfaces.py", line 511, in _post_json
    post_response = self.crud.json_post(self.model_name, data_dict)
  File "/usr/local/lib/python3.9/site-packages/pydent/interfaces.py", line 203, in json_post
    return self._json_controller(
  File "/usr/local/lib/python3.9/site-packages/pydent/interfaces.py", line 165, in _json_controller
    post_response = self.aqhttp.post(url, json_data=data)
  File "/usr/local/lib/python3.9/site-packages/pydent/aqhttp.py", line 330, in post
    return self.request(
  File "/usr/local/lib/python3.9/site-packages/pydent/aqhttp.py", line 255, in request
    response = requests.request(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
```

**Comment by bjkeller** [comment]
fixed by https://github.com/aquariumbio/pfish/commit/c45f3289e13d2df3cb2b526d8310d4b765f57b65
